### ISSUE TITLE
Support for server-only/client-only (feature)

### ISSUE THREAD

**Issue by sfPlayer1** [McJtyMods/TheOneProbe#18]
Considering the nature of this mod, it'd be desirable to support the mod being absent on either side, e.g. to support Vanilla client/servers, servers without the mod or clients with severe memory constraints.

**Comment by McJty** [comment]
A client side version of this mod might be possible but is a bit hard right now given that it is fully designed around blocks giving information server side. Of course on a vanilla server that doesn't matter much as there the blocks wouldn't add information themselves anyway. But still. I have to think about this

**Comment by tterrag1098** [comment]
I think the more important case is the other way around. It should be optional for clients to have installed on servers with the mod.

**Comment by xela-zone** [comment]
Any update on this?

**Comment by McJty** [comment]
Not really. It is a bit complicated to change this right now I'm afraid and I don't really see the benefit

**Comment by janagyjr** [comment]
Is this still a feature that won't happen? I enjoy having The One Probe and would like it on 'vanilla' modded clients to use on vanilla SS/MP. If so, I'll go back to using WAILA.

**Comment by McJty** [comment]
No sorry. This is fundamentally not how TOP works.
