### ISSUE TITLE
[1.10.2]Error:theoneprobe:default

### ISSUE THREAD

**Issue by b0bst3r** [McJtyMods/TheOneProbe#62]
When looking at any Inductive Automation machines and tanks, not sure what's supposed to be here.

http://i.imgur.com/ZFOIbcr.png

theoneprobe-1.10-1.1.4
InductiveAutomation-1.10.2-5.2.0

**Comment by McJty** [comment]
I need the contents of your log

**Comment by b0bst3r** [comment]
Forge log, man it's a messy one - http://pastebin.ubuntu.com/23293911/

**Comment by McJty** [comment]
Hmm was that a log that occurred when that error displayed above? Because I see nothing relevant in it and there should be.

**Comment by HalcyonSpectre** [comment]
I have the same error everytime I point at any IC2 machine. Any way to hide it?

**Comment by McJty** [comment]
These kinds of bugs are usually not bugs in The One Probe but in the mod itself not handling something correctly

**Comment by ghost** [comment]
Hey @McJty I'm getting this issue every block I look, MC 1.18.1, TOP 1.18-5.1.0 .I'd be happy to provide more info, please tell me how I can help you

**Comment by McJty** [comment]
TOP 1.18-5.1.0 is for 1.18.2. Either upgrade Minecraft or else downgrade TOP
